### ISSUE TITLE
Add more projects

### ISSUE THREAD

**Issue by shinytang6** [SJTU-SCS/awesome-scs#1]
All projects of the 2016 level software engineering course are here : [https://github.com/SE407-2017](https://github.com/SE407-2017)
You can add them to the list :)

**Comment by wangjksjtu** [comment]
Thanks, I will add them to the list. Could you recommend some amazing projects in SE407-2017?

**Comment by shinytang6** [comment]
e.g. [https://github.com/SE407-2017/FinalProject-library-seats-reservation](https://github.com/SE407-2017/FinalProject-library-seats-reservation)  is a good repo :)

**Comment by wangjksjtu** [comment]
Thanks :>
