### ISSUE TITLE
[bug] SE407-2017 organization has been deleted

### ISSUE THREAD

**Issue by hebingchang** [SJTU-SCS/awesome-scs#16]
2017年软件工程(SE407)课程的 organization (https://github.com/SE407-2017) 已被删除，所有指向该组织的链接将不可用。

> This email is to confirm that the ‘SE407-2017’ organization has been deleted from GitHub by ‘haonan2012’. Your organization’s repositories and content have been deleted from the system. You can reply directly to this email if you have any questions or feedback, we’d love to hear from you.

**Comment by shinytang6** [comment]
讲道理为啥这个人能删组织。。我记得owner只有老师一个把

**Comment by hebingchang** [comment]
> 讲道理为啥这个人能删组织。。我记得owner只有老师一个把

可能当时把几个组长也设成 owner 了，时间太久记不太清了。。

**Comment by hebingchang** [comment]
Organization (https://github.com/SE407-2017) has been restored. Issue closed.
